services:
  # PostgreSQL Database Service
  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: dockerfiles/db.Dockerfile
    restart: unless-stopped  # Automatically restart unless manually stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - healthcare_network

  # Go API Service
  api-service:
    # container_name: api-service
    build:
      context: .
      dockerfile: dockerfiles/service.Dockerfile
    restart: always
    env_file: .env
    environment:
      - DATABASE_URL=${DATABASE_URL} # Optional, since env_file directive loads environment variables from a .env
    # ports:
    #   - "8080:8080"  # Expose port 8080 on the host
    depends_on:
      - postgres
    networks:
      - healthcare_network

  # Nginx Service for Reverse Proxy
  nginx:
    container_name: nginx-reverse-proxy
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "3000:3000"
    depends_on:
      - api-service
    networks:
      - healthcare_network

# Volumes
volumes:
  postgres_data:

# Networks
networks:
  healthcare_network:
    driver: bridge
