services:
  # PostgreSQL Database Service
  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: dockerfiles/db.Dockerfile
    restart: unless-stopped  # Automatically restart unless manually stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - healthcare_network
    healthcheck:
      test: ["CMD", "pg_isready --username=${POSTGRES_USER} --dbname=${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Go API Service
  api-service:
    # container_name: api-service
    build:
      context: .
      dockerfile: dockerfiles/service.Dockerfile
    restart: always
    env_file: .env
    environment:
      - DATABASE_URL=${DATABASE_URL} # Optional, since env_file directive loads environment variables from a .env
    # ports:
    #   - "8080:8080"  # Expose port 8080 on the host
    depends_on:
      - postgres
    networks:
      - healthcare_network
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "postgres", "-p", "${DB_PORT}", "-U", "${POSTGRES_USER}"]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 30s
    entrypoint: ["sh", "-c", "until pg_isready -h postgres -p 5432 -U ${POSTGRES_USER}; do sleep 2; done; /app"]  # Wait for DB before starting app

  # Nginx Service for Reverse Proxy
  nginx:
    container_name: nginx-reverse-proxy
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "3000:3000"
    depends_on:
      - api-service
    networks:
      - healthcare_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - healthcare_network

# Volumes
volumes:
  postgres_data:

# Networks
networks:
  healthcare_network:
    driver: bridge
